blog/urls.py
from django.urls import path
from blog.views import ArticleListView

urlpatterns = [
    path('article_list/', ArticleListView.as_view(), name='article_list'),
]

hotwheelsbg/urls.py
from django.contrib import admin

from django.urls import path, include
from login import views
from django.views import generic as generic_views
import shop.views as shop_views

from blog.views import ArticleListView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', shop_views.all_products, name='all_products'),      # Matches the root URL
    path('blog/', shop_views.blog, name='blog'),
    path('about/', shop_views.about, name='about'),
    path('contact_page/', shop_views.contact_page, name='contact_page'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),  # Include your app's URL patterns here
    path('article_list/', ArticleListView.as_view(), name='article_list'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from login import views
from django.views import generic as generic_views



urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('home/', views.home, name='home'),    # Matches /home/ URL
]

blog/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='blog_images/')

    def __str__(self):
        return self.title

login/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models



class Article(models.Model):
    name = models.CharField(max_length=30)
    created_on = models.DateTimeField(auto_now_add=True)


class Product(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    image_url = models.CharField(max_length=900)
    price = models.FloatField()
    quantity = models.IntegerField()
    category = models.CharField(max_length=30)
    subcategory = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.CharField(max_length=30)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.user


class Order(models.Model):
    user = models.CharField(max_length=30)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user



class Contact(models.Model):
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=254)
    message_subject = models.CharField(max_length=100, blank=True)
    message_body = models.TextField(max_length=3000, blank=True)

shop/forms.py
from django import forms


from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'message_subject', 'message_body']

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from blog.models import Article

class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'  # Create this template
    context_object_name = 'articles'
    ordering = ['-publication_date']

login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms
import random
from django.contrib.auth.models import User



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


def login_view(request):
    if request.method == 'POST':
        # Assuming you have a custom LoginForm defined in forms.py
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Authenticate the user
            user = authenticate(username=username, password=password)

            if user is not None:
                # Log the user in if authentication is successful
                login(request, user)
                return render(request, 'home.html')  # Redirect to home page after successful login
            else:
                # Authentication failed, handle the error accordingly
                error_message = "Invalid username or password."
        else:
            # Form data is invalid, handle the error accordingly
            error_message = "Invalid form data. Please check the input fields."
    else:
        # If it's not a POST request, display an empty login form
        form = LoginForm()
        error_message = None

    return render(request, './login.html', {'form': form, 'error_message': error_message})


def logout_view(request):
    # Your logout view logic here
    return render(request, './logout.html')

def home(request):
    # Your logout view logic here
    return render(request, './home.html')
def index(request):
    suffix = random.randint(1, 1000000)
    User.objects.create(
        username=f'admin_{suffix}',
        password='*31321sdJ',
    )
    # Your logout view logic here
    return render(request, './index.html')

shop/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from shop.models import Product, Contact

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views import generic as generic_views

from shop.forms import ContactForm
from .models import Product  # Import your Product model
class IndexView(generic_views.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context
@login_required  # Requires user to be logged in to access this view
def wishlist_view(request):
    # Your view logic for the wishlist page goes here
    return render(request, 'wishlist.html')  # Replace 'wishlist.html' with your actual template

@login_required  # Requires user to be logged in to access this view
def cart_view(request):
    # Your view logic for the cart page goes here
    return render(request, 'cart.html')  # Replace 'cart.html' with your actual template

def all_products(request):
    products = Product.objects.all()
    return render(request, 'all_products.html', {'products': products})

def blog(request):

    return render(request, 'blog.html')
def about(request):

    return render(request, 'about.html')

def contact_page(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Create a new Contact instance and populate it with the form data
            contact = Contact(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                message_subject=form.cleaned_data['message_subject'],
                message_body=form.cleaned_data['message_body']
            )

            # Save the contact to the database
            contact.save()

            # Section for E-mail sending:
            subject = 'New Contact Submission from ' + form.cleaned_data['first_name']
            # message = 'You have received a new contact form submission from ' + form.cleaned_data['first_name'] + ' ' + \
            #           form.cleaned_data['last_name'] + '. Email: ' + form.cleaned_data[
            #               'email'] + '. Message Subject: ' + \
            #           form.cleaned_data['message_subject'] + '. Message Body: ' + form.cleaned_data['message_body']
            # send_mail(subject, message, 'iv.svetlin@outlook.com', ['isvetllin@gmail.com'])
            # End of E-mail sending section.

            # Redirect or show a success message
            return render(request, 'contact_success.html')
    else:
        form = ContactForm()

    return render(request, 'contact_page.html', {'form': form})

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .col-md-8 {
       width: 100%;
    }
</style>
<div class="container">
    <header class="blog-header py-3">

    </header>
</div>
<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom"> About page</h3>
   <div class="container mt-5">
        <h1 class="mb-4">About Us</h1>

        <p>Welcome to HotReels, your one-stop destination for all things HotWheels! We are passionate about bringing the thrill and excitement of HotWheels to collectors, enthusiasts, and kids of all ages. Whether you're a die-hard HotWheels collector or looking for the perfect gift, we've got you covered.</p>

        <h2 class="mt-4">Our Mission</h2>

        <p>At HotReels, our mission is simple: to provide you with the widest selection of HotWheels toys, accessories, and collectibles, all in one convenient place. We are committed to delivering exceptional products and service that cater to your HotWheels obsession.</p>

        <h2 class="mt-4">Why Choose Us?</h2>

        <ol>
            <li><strong>Unrivaled Selection:</strong> We boast an extensive collection of HotWheels cars, sets, and accessories. From classic vintage models to the latest releases, we have something for every HotWheels enthusiast.</li>
            <li><strong>Quality Assurance:</strong> We understand the value of quality when it comes to collectibles. That's why we source our HotWheels products from trusted manufacturers and suppliers, ensuring you receive authentic, high-quality items every time.</li>
            <li><strong>Competitive Pricing:</strong> We believe that everyone should have access to their favorite HotWheels toys without breaking the bank. Our competitive pricing ensures you get the best deals and discounts on a wide range of products.</li>
            <li><strong>Easy and Secure Shopping:</strong> Our user-friendly website is designed to make your shopping experience seamless and secure. Shop with confidence, knowing that your personal information is protected.</li>
            <li><strong>Dedicated Customer Support:</strong> Have a question or need assistance? Our friendly customer support team is here to help you every step of the way. We're just a click or phone call away.</li>
            <li><strong>Fast Shipping:</strong> We understand that you can't wait to get your hands on your new HotWheels treasures. We offer fast and reliable shipping options to get your order to your doorstep as quickly as possible.</li>
            <li><strong>Passionate Community:</strong> We're not just a store; we're a community of HotWheels enthusiasts. Join us on social media and forums to connect with like-minded collectors and stay up-to-date with the latest HotWheels news and releases.</li>
        </ol>

        <h2 class="mt-4">Our Story</h2>

        <p>HotReels was founded by an avid HotWheels collector who wanted to share his passion with the world. We know firsthand the joy and excitement that HotWheels can bring, and we're dedicated to helping others experience that same thrill.</p>

        <p>From humble beginnings, we have grown into a trusted source for HotWheels toys and accessories. Our team is constantly on the lookout for the hottest releases and the rarest finds to add to our collection. We are driven by our love for HotWheels and our desire to make collecting these iconic cars accessible to everyone.</p>

        <p>Thank you for choosing HotReels as your HotWheels destination. We look forward to serving you and being a part of your HotWheels journey. Happy collecting!</p>
    </div>
        </div>
    </div>
</main>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+JKT8UR/O4Ft3n2M1OG5f5Vr5zQ3u6k1ksCkC5/K5h5I5F5l" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-pzjw8f+ua7Kw1TIq0v8FqFjcJ6pajs/rfdfs3SO+kX1CKmLq5k5F5b5F5F5R5f5g5R5" crossorigin="anonymous"></script>
{% endblock content %}

templates/all_products.html
{% extends 'base.html' %}  <!-- If you have a base template, you can extend it. If not, remove this line. -->
{% load static %}  <!-- If you have a base template, you can extend it. If not, remove this line. -->
{% block content %}
    <div style="height: 50px; visibility: hidden"></div>
    <div class="container">
        <div class="row">
            {% for product in products %}
                <div class="col">
<div class="card shadow-sm" style="height: 100%;">
    <img src="{{  product.image_url }}" class="bd-placeholder-img card-img-top" style="width: 100%; height: 100%; object-fit: cover;" alt="Toy...">
{#   {% static product.image_url %} #}

                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="card-text">Price: BGN {{ product.price }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Buy</button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
</svg></button>
                                </div>
                                <small class="text-muted">Quantity: {{ product.quantity }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
        <div style="height: 50px; visibility: hidden"></div>

{% endblock %}

templates/article_list.html
<!-- blog/templates/blog/article_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <header class="blog-header py-3">
    </header>
</div>
<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom">Articles</h3>
            {% for article in articles %}
            <div class="article">
                <h2>{{ article.title }}</h2>
<p><img src="{{ article.image.url }}" alt="{{ article.title }}" class="img-fluid"></p>
                <p>{{ article.content }}</p>

                <p>Published on {{ article.publication_date }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Headers · Bootstrap v5.0</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/headers/">
    {% load static %}


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        main {
            flex: 1;
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>
<body>
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'all_products' %}" class="nav-link px-2 text-secondary">Home</a></li>
<li><a href="{% url 'blog' %}" class="nav-link px-2 text-white">Blog</a></li>
                <li><a href="{% url 'about' %}" class="nav-link px-2 text-white">About</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
            </form>

            <div class="text-end">
{% if user.is_authenticated %}
    <button type="button" class="btn btn-warning">Sign out</button>
    <a href="#">
        <span class="bi bi-heart">Wishlist</span>
    </a>
    <a href="#">
        <span class="bi bi-cart">Cart</span>
    </a>
{% else %}
    <button type="button" class="btn btn-outline-light me-2">Login</button>
    <button type="button" class="btn btn-warning">Sign-up</button>
{% endif %}

            </div>
        </div>
    </div>
</header>
<main>
    <div>
        {% block content %}
        {% endblock content %}
        {% block success %}
        {% endblock success %}
    </div>
</main>
{% include 'footer.html' %}
</body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .col-md-8 {
       width: 100%;
    }
</style>
<div class="container">
    <header class="blog-header py-3">

    </header>
</div>
<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom"> Articles</h3>
            {% block thearticle %}
            {% endblock thearticle %}
            {% block article_lists %}
            {% endblock article_lists %}
         </div>
    </div>
</main>
{% endblock content %}

templates/contact_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
    .hidden { visibility: hidden; padding-top:50px; }
    </style>
<div class="col-md-8 col-lg-6 mx-auto">
<div class="hidden"></div>
    <div class="card bg-transparent">
        <div class="card-body">
            <h4 class="card-title text-center">Contact Form</h4>

            <div class="text-left">
               <form method="POST" action="{% url 'contact_page' %}" class="my-4">

                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="id_first_name" class="form-label">First name</label>
                        <input type="text" name="first_name" maxlength="100" class="form-control" id="id_first_name">
                    </div>

                    <div class="mb-3">
                        <label for="id_last_name" class="form-label">Last name</label>
                        <input type="text" name="last_name" maxlength="100" class="form-control" id="id_last_name">
                    </div>

                    <div class="mb-3">
                        <label for="id_email" class="form-label">Email</label>
                        <input type="email" name="email" maxlength="254" required class="form-control" id="id_email">
                    </div>

                    <div class="mb-3">
                        <label for="id_message_subject" class="form-label">Message Subject</label>
                        <input type="text" name="message_subject" maxlength="100" class="form-control" id="id_message_subject">
                    </div>

                    <div class="mb-3">
                        <label for="id_message_body" class="form-label">Message Body</label>
                        <textarea name="message_body" class="form-control" rows="4" id="id_message_body"></textarea>
                    </div>

                    <button type="submit" class="btn btn-secondary btn-block">Submit</button>
                </form>
            </div>
        </div>
    </div>
            <div class="hidden"></div>
</div>
{% endblock content %}

templates/contact_success.html
{% extends 'base.html' %}
{% load static %}

{% block success %}
<p style="color: darkseagreen"> Successfully submitted! </p>
<p style="color: darkseagreen"> Your message has been sent. </p>
<p style="color: darkseagreen"> We will contact you soon. </p>
{% endblock success %}

templates/footer.html
<doctype html>
    <html lang="en">
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>

        {% load static %}
        <style>
            footer {
                padding: 32px 0px 0px 0px;
              {# Use when the footer is to be replaced by an image: #}
                {#background: url('https://img.freepik.com/free-vector/modern-flowing-blue-wave-banner-white-background_1035-18960.jpg?q=10&h=200') no-repeat center center;#}
                {#background-size: cover;#}
                {# Light gray footer background:: #}

    --bs-bg-opacity: 0.5;
    background-color: rgba(var(--bs-dark-rgb),var(--bs-bg-opacity))!important;

                position: relative;
                z-index: 6;
                font-family: Arial, Helvetica, sans-serif;
            }
        </style>
    </head>

    <footer>
        <div class="footer-line-1">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <div class="footer-wrapper-logo-social">
                            <a href="/" class="mini-logo" title="HotReels.com">
                                <img style="width: 120px; height: auto;"
                                     src="{% static 'img/hwnovector.png' %}"
                                     alt="HotReels.com">
                            </a>
                            <a href="https://www.facebook.com/HotReels.com" target="_blank"><i class="fab fa-facebook"
                                                                                               style="color: #fff;"></i></a>
                            <a href="https://www.instagram.com/HotReels.com/" target="_blank"><i
                                    class="fab fa-instagram" style="color: #fff;"></i></a>
                            <a href="https://www.tiktok.com/@HotReels.com" target="_blank"><i class="fab fa-tiktok"
                                                                                              style="color: #fff;"></i></a>
                            <a href="https://www.youtube.com/@izigraiskukata" target="_blank"><i class="fab fa-youtube"
                                                                                                 style="color: #fff;"></i></a>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                        <div class="footer-wrapper-payment-logos">
                            <span style="color: #fff; margin-right: 20px;">Начин на плащане</span>
                            <div>
                                <img src="{% static 'paymentmethods/maestro.png' %} "
                                     style="background: #fff; width: 40px; height: auto; border-radius: 6px;">
                                <img src="{% static 'paymentmethods/mcard.png' %}"
                                     style="background: #fff; width: 40px; height: auto; border-radius: 6px;">
                                <img src="{% static 'paymentmethods/visa.png' %}"
                                     style="background: #fff; width: 40px; height: auto; border-radius: 6px;">
                                <img src="{% static 'paymentmethods/visael.png' %}"
                                     style="background: #fff; width: 40px; height: auto; border-radius: 6px;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>
            <div class="wide-area info-cols">
                <div class="container">
                    <div class="row">
<a href="{% url 'contact_page' %}">
        <span>Контакт</span>
    </a>



                        <!--<span class="razer-distributor"></span>-->
                    </div>
                </div>
            </div>
            <div class="container">
                <div style="border-bottom: 1px solid #fff;"></div>
            </div>
        </div>


        <div class="wide-area copy-rights">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-8 col-md-6">
                    <span class="copy">© 2023 HotReels All Rights Reserved                        &nbsp; | &nbsp;
                        <!-- <a href="">Карта на сайта</a> -->
                    </span>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-6 websites">
                   <span>
                       <a href="" target="_blank" style="color: #fff;"></a><span style="color: #fff;"> | </span>
                   </span>
                    </div>
                </div>
            </div>
        </div>


    </footer>
    </html>

templates/home.html
<html>
    <body>
        <p>
            home            home            home
        </p>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}  <!-- If you have a base template, you can extend it. If not, remove this line. -->
{% load static %}  <!-- If you have a base template, you can extend it. If not, remove this line. -->
{% block content %}
    <div style="height: 50px; visibility: hidden"></div>
    <div class="container">
        <div class="row">
            {% for product in products %}
                <div class="col">
<div class="card shadow-sm" style="height: 100%;">
    <img src="{{  product.image_url }}" class="bd-placeholder-img card-img-top" style="width: 100%; height: 100%; object-fit: cover;" alt="Toy...">
{#   {% static product.image_url %} #}

                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="card-text">Price: BGN {{ product.price }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Buy</button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
</svg></button>
                                </div>
                                <small class="text-muted">Quantity: {{ product.quantity }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
        <div style="height: 50px; visibility: hidden"></div>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
</head>
<body>
    <h1>Login page</h1>
    <form method="post" action="{% url 'home' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

templates/logout.html
<html>
    <body>
        <p>
            Paragraph
        </p>
    </body>
</html>

templates/sign-in/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Signin Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">



    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">

<main class="form-signin">
<form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'register_view' %}" method="post">
  {% csrf_token %}
  <!-- Rest of the form remains the same -->

    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>


    
  </body>
</html>

web_project/login/__pycache__/templates/home.html
<html>
    <body>
        <p>
            home
        </p>
    </body>
</html>

web_project/login/__pycache__/templates/login.html
<html>
    <body>
        <p>
            Paragraph
        </p>
    </body>
</html>

web_project/login/__pycache__/templates/logout.html
<html>
    <body>
        <p>
            Paragraph
        </p>
    </body>
</html>